confluentinc/kafka-connect-datagen

- LICENSE
The source code already uses the ASL 2.0, and the Confluent Hub metadata references ASL 2.0 as well. However, the convention is for the GitHub repo to include a `LICENSE` file, and that file should be included in the archive.
> CC-3545: Add missing license file to the GitHub repo

- CHANGELOG.md
- pom.xml
Avro 1.8.2 contains a critical bug (https://issues.apache.org/jira/browse/AVRO-2122). Downgrading to 1.8.1 to reflect Confluent Platform 5.x and to avoid this potential problem.
> MIINOR: Downgrade to Avro 1.8.1

- pom.xml
- src/main/java/io/confluent/kafka/connect/datagen/DatagenTask.java
- src/test/java/io/confluent/kafka/connect/datagen/DatagenConnectorTest.java
- src/test/java/io/confluent/kafka/connect/datagen/DatagenTaskTest.java
- src/test/resources/log4j.properties
Unit tests now verify that the connector can generate records for each of the provided quickstart schemas, and that the connector generates the correct task configs.
> Add unit tests for connector and tasks

- README.md
It's easier for end-users to have the config listed in the docs, plus not all users will be comfortable reading/guessing at what the Java code linked to means.
> Include parameters in readme

- pom.xml
The `common-utils` artifact is actually required at runtime and not, as the comment above it in the POM implies, inherited unnecessarily. The dependency chain goes from the Avro converter (which is used to convert generated Avro data into a format usable for Connect records) to the `io.confluent:common-config` artifact to the `common-utils` artifact. As a result, if this artifact is not included in the plugin archive for this connector and is not present on the Connect worker's classpath, the connector will fail.
The changes here remove the custom scoping for the `common-utils` artifact, which causes it to be included in the Confluent Hub archive file and allows this connector to be used as an isolated plugin that does not rely on dependencies being present in the Connect worker's …
> MINOR: Remove test scoping for common-utils dependency

- Makefile
- README.md
Makefile defaults a kafka connect datagen version, updated to our latest build
> update default datagen version in makefile

- pom.xml
The `kafka-connect-avro-converter` dependency is added to the POM for this connector so that the `AvroData` class can be used to convert from Avro to the Connect record format, but the actual `AvroConverter` class (or any of its nested classes) is never used. However, the Connect framework will still sometimes pick up the `AvroConverter` present in the plugin archive for the datagen connector and try to use that as an actual converter plugin, even though most of the transitive dependencies for the `kafka-connect-avro-converter` dependency are excluded, which then causes classloading issues.
The changes here are a bit of a hack: they alter the Confluent Hub archive generated during the connector build by removing the `AvroConverter` class (and all of its nested classes) from the …
> CC-7254: Remove AvroConverter plugin from Confluent Hub archive

- pom.xml
Backports the changes from https://github.com/confluentinc/kafka-connect-datagen/pull/31 to the `0.1.x` branch.
> MINOR: Backport CC-7254 "Remove AvroConverter plugin from Confluent Hub archive"

- src/main/java/io/confluent/kafka/connect/datagen/DatagenTask.java
- src/test/java/io/confluent/kafka/connect/datagen/DatagenTaskTest.java
The key schema is hard-coded as STRING_SCHEMA, specifically non-optional.
This makes it impossible to specify `null` as a key, to trigger round-robin/sticky partitioning.
It also forces the key field to always refer to a string field, and not a more complex key.
This change infers the schemas from the key field itself, or defaults to
OPTIONAL_STRING_SCHEMA schema and null value for the key if no field is specified.
The test infrastructure for this was already included, but was disabled because this feature was not implemented.
Signed-off-by: Greg Harris <gregh@confluent.io>
> CC-7434: Infer key schemas from value schemas, change default key schema

- Makefile
Previously we published without the operator rev ver number.  I deleted invalid
tags from the dockerhub repository as well.
> DEVX-1671 Fixes issue with operator version numbers in Makefile

- config/connector_inventory.config
- config/connector_product.config
- src/main/java/io/confluent/kafka/connect/datagen/DatagenTask.java
- src/test/java/io/confluent/kafka/connect/datagen/DatagenTaskTest.java
Adds missing quickstarts
Adds enum values for missing quickstarts and tests.
* Added two unit tests to verify.
* Added two sample configs, and verified with local confluent platform 5.5.1
- [X ] Unit tests
> DEVX-1923: Add missing quickstarts (Inventory and Product)

- pom.xml
- src/test/java/io/confluent/kafka/connect/datagen/DatagenTaskTest.java
Want to build a new version of the connector off of the 6.0 CP libraries
Update pom.xml and execute a release building 0.3.4 datagen version
No code changes in the datagen code with this change, only the base libraries have been upgraded to 6.0.  Unit tests pass
After building the full datagen docker imags, will validate new images in Confluent Integration Arch demos and examples.
> DEVX-2070: Changes prior to building and publishing new 6.0 based datagen images

- README.md
The README references outdated versions of the connector and CP
Updated the documentation.  Pushing to the release branch and will follow with a push to master
> DEVX-2085: Updating docs to late model version numbers

- Makefile
- README.md
https://confluentinc.atlassian.net/browse/DEVX-2372
Branch and DEVX Jira tickets are off, apologies. Created image locally and tested with examples/ccloud, and cp-all-in-one-community. 
@ybyzek and @rspurgeon One question prior to officially submitting this PR--can we push new versions of the connector to confluent hub? Should I update the pom.xml confluent version and package version in this PR even though I may not be able to publish those packages to confluent hub? For the record, I was able to update the pom.xml (minor change necessary `confluent.version` --> `confluent.version.range`), and create the package. All tests passed during compiling. 
Also is here when I should update the docker-compose? That looks pretty out of date. 
Will publish images once merged (ie run `make …
> DEVX-2372: Build and publish new kafka-connect-datagen 6.1.0 images and update all demos on 6.1.0-post branch

- README.md
- src/main/java/io/confluent/kafka/connect/datagen/DatagenTask.java
- src/test/java/io/confluent/kafka/connect/datagen/DatagenTaskTest.java
https://github.com/confluentinc/kafka-connect-datagen/issues/29
Add an explicit check to see if field specified in config `schema.keyfield` exists in the provided schema. If it isn't present, throw an appropriate error instead of failing with a [NPE here](https://github.com/confluentinc/kafka-connect-datagen/blob/c661b0d76eab491d2d9dfe6a1482c65141caaea6/src/main/java/io/confluent/kafka/connect/datagen/DatagenTask.java#L227)
Added a unit test
- Should we add a config validation for this? We'd probably need to add some schema parsing and validation too. Currently, the only validation that exists is a check to verify that not more than 1 out of `schema.filename`, `schema.string` and `quickstart` is set. If a bad schema is provided, the connector will start and immediately fail.
> Fail with appropriate message instead of aborting with NPE when field specified in schema.keyfield doesn't exist in the schema

- pom.xml
- src/main/java/io/confluent/kafka/connect/datagen/ConfigUtils.java
- src/main/java/io/confluent/kafka/connect/datagen/DatagenConnector.java
- src/main/java/io/confluent/kafka/connect/datagen/DatagenConnectorConfig.java
- src/main/java/io/confluent/kafka/connect/datagen/DatagenTask.java
- src/test/java/io/confluent/kafka/connect/datagen/DatagenConnectorTest.java
- src/test/java/io/confluent/kafka/connect/datagen/DatagenTaskTest.java
- src/test/resources/invalid_users_schema.avro
The connector fails immediately after starting if provided schema (via any of the three schema sources) or schema key field is invalid.
Add schema validations, so that the connector doesn't start with an invalid schema or schema key field.
Added unit tests
- Should this go to a new minor version branch (0.5.x) as this isn't a bugfix and according to semver patch version bumps should only be for bug fixes
> Add validations for quickstart, schema.string, schema.filename

- src/main/resources/pageviews_schema.avro
- src/main/resources/stock_trades_schema.avro
- src/main/resources/users_array_map_schema.avro
- src/main/resources/users_schema.avro
* https://confluentinc.atlassian.net/browse/CCLOG-402
{0,1} and ? are java quantifiers which allow user to specify the number of occurrences to match against. Below are some commonly used quantifiers in Java. 
```
X*        Zero or more occurrences of X
X?        Zero or One occurrences of X
X+        One or More occurrences of X
X{n}      Exactly n occurrences of X 
X{n, }    At-least n occurrences of X
X{n, m}   Count of occurrences of X is from n to m
```
So basically regex X{0,1} and X? implies same thing, i.e, the character X should occur once or not at all. For datagen connector, this quantifier is redundant as the character X is occurring always once. So removal of these quantifiers should not effect the functionality of connector - it would produce same records as earlier 
Remove …
> CCLOG-402: Remove redundant quantifiers from quickstart schema template

- pom.xml
Pulls in the fix from https://github.com/confluentinc/avro-random-generator/pull/22, which is included in the recent [0.4.1 release](https://github.com/confluentinc/avro-random-generator/commits/v0.4.1).
> MINOR: Bump Avro Random Generator dependency to fix regex string generation bug

- pom.xml
- src/main/java/io/confluent/kafka/connect/datagen/DatagenConnector.java
- src/main/java/io/confluent/kafka/connect/datagen/DatagenConnectorConfig.java
- src/main/java/io/confluent/kafka/connect/datagen/DatagenTask.java
- src/main/java/io/confluent/kafka/connect/datagen/VersionUtil.java
https://nvd.nist.gov/vuln/detail/CVE-2020-36518
Upgraded the common version, to bring in the version of jackson-databind which has the fix for this cve.
Also had to import `confluent-log4j` to avoid the following error in tests, where log4j dependency wasn't being pulled in. 
```
[ERROR] Tests run: 14, Failures: 0, Errors: 14, Skipped: 0, Time elapsed: 0.01 s <<< FAILURE! - in io.confluent.kafka.connect.datagen.DatagenTaskTest
[ERROR] io.confluent.kafka.connect.datagen.DatagenTaskTest.shouldGenerateFilesForUsersQuickstart  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NoClassDefFoundError: org/apache/log4j/Level
at io.confluent.kafka.connect.datagen.DatagenTaskTest.<clinit>(DatagenTaskTest.java:58)
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Level
at …
```
> CCLOG-1921 Fix for CVE-2020-36518

- src/main/java/io/confluent/kafka/connect/datagen/DatagenTask.java
- src/test/java/io/confluent/kafka/connect/datagen/DatagenTaskTest.java
Complex schema type such as array, struct, maps having default value as null is causing a NPE
When a complex schema type is received, we further expand it to get to native data types by typecasting the value.
Before typecasting the value, we should check for the null value and return if a null value is found
> RCCA-8574: Handle default value as null for complex data types

- pom.xml
https://nvd.nist.gov/vuln/detail/CVE-2023-2976
Increasing guava dependency version to recommended 32.0.1-jre.
All existing unit tests run fine.
> CC-21503 Increase guava version to 32.0.1-jre to address CVE-2023-2976

- Jenkinsfile
jenkins job is failing because of pint merge. Fixing pint merge: https://jenkins.confluent.io/job/confluentinc/job/kafka-connect-datagen/job/master/
> CC-24021: Enable pint merge

- pom.xml
```
[CVE-2024-25710](https://nvd.nist.gov/vuln/detail/CVE-2024-25710) : Loop with Unreachable Exit Condition ('Infinite Loop') vulnerability in Apache Commons Compress.This issue affects Apache Commons Compress: from 1.3 through 1.25.0. Users are recommended to upgrade to version 1.26.0 which fixes the issue.
```
Upgrade package commons.compress to 1.26.0
> CC-25375: CVE fix for apache common-compress package

- src/main/java/io/confluent/kafka/connect/datagen/ConfigUtils.java
Currently validation request throws 500 if schema.string value have two fields with same name.
SchemaParseException only cover  specific error related to schema parsing but there is super class AvroRuntimeException which covers more broder issue while parsing schema. For example, Duplicate keys in schema. 
https://github.com/apache/avro/blob/release-1.11.4/lang/java/avro/src/main/java/org/apache/avro/SchemaParseException.java#L22
Tested with below curl
```
curl 'http://localhost:9021/api/connect/connect-default/connector-plugins/io.confluent.kafka.connect.datagen.DatagenConnector/config/validate' \
-X 'PUT' \
-H 'Accept: */*' \
-H 'Accept-Language: en-US,en;q=0.9' \
-H 'Connection: keep-alive' \
-H 'Content-Type: application/json' \
-H 'Origin: http://localhost:9021' \
-H 'Referer: …
```
> Fix schema parsing issue
